In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [4]:

df = pd.read_csv(r"D:\ML project end to end\notebook\data\stud.csv")

In [5]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
df.shape

(1000, 8)

In [7]:
df.isnull().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race_ethnicity               1000 non-null   str
 2   parental_level_of_education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test_preparation_course      1000 non-null   str
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [10]:
df.nunique()

gender                          2
race_ethnicity                  5
parental_level_of_education     6
lunch                           2
test_preparation_course         2
math_score                     81
reading_score                  72
writing_score                  77
dtype: int64

In [11]:
df.describe()

       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [12]:
print("Categories in 'gender' variable:", end=" ")
print(df["gender"].unique())

print("Categories in 'race_ethnicity' variable:", end=" ")
print(df["race_ethnicity"].unique())

print("Categories in 'parental level of education' variable:", end=" ")
print(df["parental_level_of_education"].unique())

print("Categories in 'lunch' variable:", end=" ")
print(df["lunch"].unique())

print("Categories in 'test preparation course' variable:", end=" ")
print(df["test_preparation_course"].unique())

Categories in 'gender' variable: <StringArray>
['female', 'male']
Length: 2, dtype: str
Categories in 'race_ethnicity' variable: <StringArray>
['group B', 'group C', 'group A', 'group D', 'group E']
Length: 5, dtype: str
Categories in 'parental level of education' variable: <StringArray>
[ 'bachelor's degree',       'some college',    'master's degree',
 'associate's degree',        'high school',   'some high school']
Length: 6, dtype: str
Categories in 'lunch' variable: <StringArray>
['standard', 'free/reduced']
Length: 2, dtype: str
Categories in 'test preparation course' variable: <StringArray>
['none', 'completed']
Length: 2, dtype: str

In [13]:
print(df.dtypes)

gender                           str
race_ethnicity                   str
parental_level_of_education      str
lunch                            str
test_preparation_course          str
math_score                     int64
reading_score                  int64
writing_score                  int64
dtype: object

In [14]:
print(df.head())

   gender race_ethnicity parental_level_of_education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test_preparation_course  math_score  reading_score  writing_score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75

In [15]:
numeric_features = df.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = df.select_dtypes(
    include=["object", "str"]
).columns.tolist()

print("We have {} numerical features : {}".format(
    len(numeric_features),
    numeric_features
))

print("\nWe have {} categorical features : {}".format(
    len(categorical_features),
    categorical_features
))

We have 3 numerical features : ['math_score', 'reading_score', 'writing_score']

We have 5 categorical features : ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']

In [16]:
df["total_score"] = (
    df["math_score"]
    + df["reading_score"]
    + df["writing_score"]
)

df["average"] = df["total_score"] / 3

df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

In [18]:
reading_full = df[df["reading_score"] == 100]["average"].count()

writing_full = df[df["writing_score"] == 100]["average"].count()

math_full = df[df["math_score"] == 100]["average"].count()

print(f"Number of students with full marks in Maths: {math_full}")
print(f"Number of students with full marks in Writing: {writing_full}")
print(f"Number of students with full marks in Reading: {reading_full}")

Number of students with full marks in Maths: 7
Number of students with full marks in Writing: 14
Number of students with full marks in Reading: 17

In [19]:
reading_less_20 = df[df["reading_score"] <= 20]["average"].count
writing_less_20 = df[df["writing_score"] <= 20]["average"].count
math_less_20 = df[df["math_score"] <= 20]["average"].count

print(f"Number of students with less  than 20 marks in maths :{math_less_20}")
print(f"Number of students with less  than 20 marks in Writing :{writing_less_20}")
print(f"Number of students with less  than 20 marks in Reading :{reading_less_20}")

Number of students with less  than 20 marks in maths :<bound method Series.count of 17     26.000000
59      9.000000
787    29.666667
980    18.333333
Name: average, dtype: float64>
Number of students with less  than 20 marks in Writing :<bound method Series.count of 59      9.000000
327    23.333333
596    23.000000
Name: average, dtype: float64>
Number of students with less  than 20 marks in Reading :<bound method Series.count of 59    9.0
Name: average, dtype: float64>

EDA

In [ ]:
fig, axs = plt.subplots(1,2 figsize = (15,7))
plt.subplot(121)
sns.histplot(data=df, x="average", bins=30, kde= True,color="g")
plt.subplot(122)
sns.hisplot(data=df,  x="average", kde= True, hue= "gender")
plt.show