In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

In [ ]:
df = pd.read_csv("stud.csv")

In [ ]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
X = df.drop(columns=["math_score"])
y = df["math_score"]

In [ ]:
print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nInput features:")
print(X.columns.tolist())

X shape: (1000, 7)
y shape: (1000,)

Input features:
['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course', 'reading_score', 'writing_score']

In [ ]:
y = df['math_score']

In [ ]:
num_features = X.select_dtypes(exclude="object").columns
cat_features = X.select_dtypes(include="object").columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [

    ("OneHotEncoder", oh_transformer, cat_features),
    ("StandarScaler", numeric_transformer, num_features),

    ]

)

C:\Users\ibtekar mind\AppData\Local\Temp\ipykernel_15584\1246466181.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_features = X.select_dtypes(include="object").columns

In [ ]:
X = preprocessor.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state= 42)
X_train.shape, X_test.shape

((800, 19), (200, 19))

In [ ]:

import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mse)
    r2_square = r2_score(true, predicted)

    return mae, mse, rmse, r2_square

In [ ]:
model_list = []
r2_list = []

for model_name, model in models.items():

    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluate training performance
    model_train_mae, model_train_mse, model_train_rmse, model_train_r2 = evaluate_model(
        y_train, y_train_pred
    )

    # Evaluate testing performance
    model_test_mae, model_test_mse, model_test_rmse, model_test_r2 = evaluate_model(
        y_test, y_test_pred
    )

    print(model_name)
    print("Model performance for Training set")
    print("- RMSE: {:.4f}".format(model_train_rmse))
    print("- MAE: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print("\nModel performance for Test set")
    print("- RMSE: {:.4f}".format(model_test_rmse))
    print("- MAE: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))

    print("=" * 50)
    print("\n")

    model_list.append(model_name)
    r2_list.append(model_test_r2)

Linear Regression
Model performance for Training set
- RMSE: 5.3231
- MAE: 4.2667
- R2 Score: 0.8743

Model performance for Test set
- RMSE: 5.3940
- MAE: 4.2148
- R2 Score: 0.8804
==================================================


lasso
Model performance for Training set
- RMSE: 6.5938
- MAE: 5.2063
- R2 Score: 0.8071

Model performance for Test set
- RMSE: 6.5197
- MAE: 5.1579
- R2 Score: 0.8253
==================================================


Ridge
Model performance for Training set
- RMSE: 5.3233
- MAE: 4.2650
- R2 Score: 0.8743

Model performance for Test set
- RMSE: 5.3904
- MAE: 4.2111
- R2 Score: 0.8806
==================================================


K-Neighbors Regressor
Model performance for Training set
- RMSE: 5.7077
- MAE: 4.5167
- R2 Score: 0.8555

Model performance for Test set
- RMSE: 7.2530
- MAE: 5.6210
- R2 Score: 0.7838
==================================================


Decision Tree
Model performance for Training set
- RMSE: 0.2795
- MAE: 0.0187
- R2 Score: 0.9997

Model performance for Test set
- RMSE: 7.9398
- MAE: 6.3800
- R2 Score: 0.7409
==================================================


Random Forest
Model performance for Training set
- RMSE: 2.3269
- MAE: 1.8594
- R2 Score: 0.9760

Model performance for Test set
- RMSE: 6.0220
- MAE: 4.6866
- R2 Score: 0.8510
==================================================


XGBoost
Model performance for Training set
- RMSE: 1.0073
- MAE: 0.6875
- R2 Score: 0.9955

Model performance for Test set
- RMSE: 6.4733
- MAE: 5.0577
- R2 Score: 0.8278
==================================================


Cat Boost
Model performance for Training set
- RMSE: 3.0427
- MAE: 2.4054
- R2 Score: 0.9589

Model performance for Test set
- RMSE: 6.0086
- MAE: 4.6125
- R2 Score: 0.8516
==================================================


AdaBoostRegressor
Model performance for Training set
- RMSE: 5.7870
- MAE: 4.7324
- R2 Score: 0.8515

Model performance for Test set
- RMSE: 6.0712
- MAE: 4.7711
- R2 Score: 0.8485
==================================================

In [ ]:
pd.DataFrame(list(zip(model_list, r2_list)), columns=["model name", "r2_score"]).sort_values(by=["r2_score"] , ascending=False)

              model name  r2_score
2                  Ridge  0.880593
0      Linear Regression  0.880433
7              Cat Boost  0.851632
5          Random Forest  0.850969
8      AdaBoostRegressor  0.848528
6                XGBoost  0.827797
1                  lasso  0.825320
3  K-Neighbors Regressor  0.783813
4          Decision Tree  0.740937